apiVersion: postgresql.dev4devs.com/v1alpha1
kind: Database
metadata:
    name: authentication-db
    namespace: quarkus-workshop
spec:
    databaseCpu: 30m
    databaseCpuLimit: 60m
    databaseMemoryLimit: 512Mi
    databaseMemoryRequest: 128Mi
    databaseName: authentication-db
    databaseNameKeyEnvVar: POSTGRESQL_DATABASE
    databasePassword: authentication
    databasePasswordKeyEnvVar: POSTGRESQL_PASSWORD
    databaseStorageRequest: 1Gi
    databaseUser: authentication
    databaseUserKeyEnvVar: POSTGRESQL_USER
    image: centos/postgresql-96-centos7
    size: 1
