---
apiVersion: "v1"
kind: "List"
items:
    - apiVersion: "v1"
      kind: "Service"
      metadata:
          labels:
              app: "quarkus-workshop-authentication"
              version: "01"
              group: "stijnpijn"
          name: "quarkus-workshop-authentication"
      spec:
          ports:
              - name: "http"
                port: 8083
                targetPort: 8083
          selector:
              app: "quarkus-workshop-authentication"
              version: "01"
              group: "stijnpijn"
          type: "ClusterIP"
    - apiVersion: "apps/v1"
      kind: "Deployment"
      metadata:
          labels:
              app: "quarkus-workshop-authentication"
              version: "01"
              group: "stijnpijn"
          name: "quarkus-workshop-authentication"
      spec:
          replicas: 1
          selector:
              matchLabels:
                  app: "quarkus-workshop-authentication"
                  version: "01"
                  group: "stijnpijn"
          template:
              metadata:
                  labels:
                      app: "quarkus-workshop-authentication"
                      version: "01"
                      group: "stijnpijn"
              spec:
                  containers:
                      - image: "stijnpijn/quarkus-workshop-authentication:latest"
                        imagePullPolicy: "IfNotPresent"
                        name: "quarkus-workshop-authentication"
                        ports:
                            - containerPort: 8083
                              name: "http"
                              protocol: "TCP"
                        env:
                            - name: "KUBERNETES_NAMESPACE"
                              valueFrom:
                                  fieldRef:
                                      fieldPath: "metadata.namespace"

                            - name: QUARKUS_DATASOURCE_URL
                              valueFrom:
                                  configMapKeyRef:
                                      name: authentication-config
                                      key: database

                            - name: QUARKUS_HTTP_PORT
                              valueFrom:
                                  configMapKeyRef:
                                      name: authentication-config
                                      key: port


