version: "3.3"
services:
    netflix-database:
        image: "postgres:10.4"
        container_name: "netflix-database"
        ports:
            - "5432:5432"
        build:
            context: ./db-init
            dockerfile: Dockerfile

    frontend:
        container_name: "netflix-frontend"
        build:
            context: ../FrontEnd/src
            dockerfile: Dockerfile
        volumes:
            - '.:/src'
            - '/src/node_modules'
        ports:
            - 8081:4200

    video:
        container_name: "netflix-video"
        build:
            context: ../VideoService
            dockerfile: Dockerfile
        depends_on:
            - netflix-database
        ports:
            - 8085:8085

#    account:
#        container_name: "netflix-account"
#        build:
#            context: ../AccountService
#            dockerfile: Dockerfile
#        depends_on:
#          - netflix-database
#        ports:
#            - 8084:8084
#
#    authentication:
#        container_name: "netflix-authentication"
#        build:
#            context: ../AuthenticationService
#            dockerfile: Dockerfile
#        depends_on:
#            - netflix-database
#        ports:
#            - 8083:8083

