apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: stijnvanderlindennetflix 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: stijnvanderlindennetflix 
    spec:
      containers:
        - name: stijnvanderlindennetflix 
          image: netflix19062.azurecr.io/stijnvanderlindennetflix
          ports:
          - containerPort: 8080