apiVersion : apps/v1
kind: Deployment
metadata:
  name: account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - name: account
          image: netflixregistry26782.azurecr.io/account
          ports:
            - containerPort: 80
---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
        - name: authentication
          image: netflixregistry26782.azurecr.io/authentication
          ports:
            - containerPort: 80
---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: video
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video
  template:
    metadata:
      labels:
        app: video
    spec:
      containers:
        - name: video
          image: netflixregistry26782.azurecr.io/video
          ports:
            - containerPort: 80
