CREATE ROLE super WITH LOGIN PASSWORD 'super';

CREATE ROLE authentication WITH LOGIN PASSWORD 'authentication' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE DATABASE authentication_db;
GRANT ALL PRIVILEGES ON DATABASE authentication_db TO authentication ;
GRANT ALL PRIVILEGES ON DATABASE authentication_db TO super;

CREATE ROLE account WITH LOGIN PASSWORD 'account' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE DATABASE account_db;
GRANT ALL PRIVILEGES ON DATABASE account_db TO account;
GRANT ALL PRIVILEGES ON DATABASE account_db TO super;

CREATE ROLE video WITH LOGIN PASSWORD 'video' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE DATABASE video_db;
GRANT ALL PRIVILEGES ON DATABASE video_db TO video;
GRANT ALL PRIVILEGES ON DATABASE video_db TO super;

