CREATE ROLE super WITH LOGIN PASSWORD 'super';

CREATE ROLE superman WITH LOGIN PASSWORD 'superman' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE DATABASE api_gateway_db;
GRANT ALL PRIVILEGES ON DATABASE api_gateway_db TO superman ;
GRANT ALL PRIVILEGES ON DATABASE api_gateway_db TO super;

CREATE ROLE superbad WITH LOGIN PASSWORD 'superbad' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE DATABASE account_db;
GRANT ALL PRIVILEGES ON DATABASE account_db TO superbad;
GRANT ALL PRIVILEGES ON DATABASE account_db TO super;

CREATE ROLE superfight WITH LOGIN PASSWORD 'superfight' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE DATABASE fights_database;
GRANT ALL PRIVILEGES ON DATABASE fights_database TO superfight;
GRANT ALL PRIVILEGES ON DATABASE fights_database TO super;

